name: milicoreria
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.6.6 #manejador de estados
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.0
  equatable: ^2.0.5 #Permite realizar una comparacion de los objetos de manera mas profunda (Permite hacer testing)
  http: ^1.2.0 # Conectar con proveedor - Apis
  local_auth: ^2.2.0 # Acceso Biometrico
  shared_preferences: ^2.2.3
  intl: ^0.19.0 #Conversion de idiomas, enteros, fechas
  url_launcher: ^6.2.6
  awesome_dialog: ^3.2.1 #Dialogos
  package_info_plus: ^5.0.1 #obtener version code de la app
  connectivity_plus: ^5.0.0 # Verifica a que tipo de red esta conectado
  device_info_plus: ^9.1.2 #Informacion del cell,Version Sistema Operatvivo
  network_info_plus: ^4.1.0+1 #Obtener ip del celular (se deben asiganr permisos para IOS)
  cached_network_image: ^3.3.1 #Muestra imagenes desde internet y las guarda en cache
  flutter_speed_dial: ^7.0.0 #Botones flotantes, utilizado para el menu (Cerrar sesion y mas)
  permission_handler: ^11.2.1 # Solicita Permisos del dispositivo al usuario (Ubicacion,Galeria.....)
  image: ^4.1.4 #Para trabajar con imagenes de la galeria
  image_picker: ^0.8.5+3 #Obtener img de la camara o galeria
  share_plus: ^7.2.1 #Compartir aplicacion
  flutter_map: ^6.1.0
  flutter_map_location_marker: ^8.0.4
  latlong2: any
  #vibration: ^1.7.6 #vibracion device
  location: ^5.0.3
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icono.PNG"
  adaptive_icon_background: "assets/icon/icono.PNG"
  flutter_lints: ^3.0.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
